services:
  postgres:
    image: postgres:17
    container_name: checkin_management_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 212224
    volumes:
      - checkin_management_data:/var/lib/postgresql/data
    restart: always

volumes:
  checkin_management_data: